### PR TITLE
Fix live video event and remove the latencyCompensator

### PR DESCRIPTION
**Pull request by matinlotfali**
After switching to AWS Media Services, I noticed that it doesn't show the live tracker anymore. So you can't go back in the previous 8 hours anymore. It is kinda okay in my opinion. 

However, the dashboard needs to adjust some of the events that it is using to show that the video is live.

### CODE REVIEW

**Comment by mistyron** [comment]
> After switching to AWS Media Services, I noticed that it doesn't show the live tracker anymore. So you can't go back in the previous 8 hours anymore. It is kinda okay in my opinion.
> 
> However, the dashboard needs to adjust some of the events that it is using to show that the video is live.

Please see: https://mistywest.slack.com/archives/C02MGT5GK44/p1718068403460679?thread_ts=1717862617.770879&cid=C02MGT5GK44

**Comment by victorwlyu321** [comment]
LGTM!

**Review by victorwlyu321 — APPROVED** [review]
LGTM!

**Review by mistyron — COMMENTED** [review]
LGTM :+1:

**Pull request merged**
